apiVersion: v1
kind: Service
metadata:
    name: camiloestradacalidaddatosmatchapi
spec:
    type: LoadBalancer
    ports:
    - port: 3000
    selector:
        app: camiloestradacalidaddatosmatchapi
