apiVersion: v1
kind: Service
metadata:
    name: camiloestradacalidaddatosmatchapi
spec:
    type: LoadBalancer
    ports:
    - port: 8080
    selector:
        app: camiloestradacalidaddatosmatchapi
