export const  TAG_CONEXION = 'Conexiones';
export const PORT = 'PORT';
export const API_DOC = 'api/docs';
export const SECURITY_BASIC = 'basic';
export const HTTP = 'http';
export const VERSION_SWAGGER = '4.0';
export const TITLE_SWAGGER = 'Calidad Match Datos API';
export const PAGINACION_LIMIT_DEFAULT = 10;
export const PAGINACION_PAGE_DEFAULT = 1;
